### ISSUE TITLE
Add post-action

### ISSUE THREAD

**Issue by davidkarlsen** [zarnovican/aws-oidc-login-action#1]
Maybe a `post-action` should be registered which deletes the credentials file?
Like in https://github.com/evryfs/helm-ephemeral-action/blob/master/action.yml#L29

**Comment by zarnovican** [comment]
That sounds very reasonable. I will implement it over the weekend, if I will find time. Thanks for submitting the issue.

**Comment by zarnovican** [comment]
Implemented in v1.0.2 release.
